[[project]]
name = "Gester"
desc = "smart search bar with plugins"
links = [
  { name = "Gester", url = "https://github.com/demndevel/gester" },
  { name = "", url = "" },
]

[[project]]
name = ""
desc = ""
links = [
  { name = "", url = "" },
  { name = "", url = "" },
]
